const dataJson = [
  '广告 Banner',
  '常规banner、特殊banner',
  '常规banner',
  '横幅广告（Banner Ad.）是网络广告最早采用的形式，也是目前最常见的形式。',
  '首页banner',
  'banner尺寸 2560*420px，二倍图尺寸5120*840px，中心内容区域1200px；',
  '标题文字大小40px，行高48px，正常体Regular，距顶部110px，距下20px；',
  '介绍文字大小16px，行高26px，正常体Regular，距下36px；',
  '统一展示Learn more+箭头，文字大小14px。',
  'FS Seamless Wi-Fi6 Solutions',
  'Accelerate and secure your wireless connerctivity',
  'Learn more',
  '小板块专题banner',
  'banner尺寸 1920*380px（小板块的专题，如方案型专题）；',
  '标题文字大小40px，行高48px，正常体Regular，距下30px；',
  '介绍文字大小16px，行高26px，正常体Regular。',
  'FS Seamless Wi-Fi6 Solutions',
  'Accelerate and secure your wireless connerctivity',
  '特殊banner',
  '大板块专题banner',
  'banner尺寸 1920*680px（大板块的专题，如促销类专题等）；',
  '标题文字大小40px，行高48px，中粗Semibold，距下30px；',
  '介绍文字大小16px，行高26px，正常体Regular。',
  'FS Seamless Wi-Fi6 Solutions',
  'Accelerate and secure your wireless connerctivity',
  '表单页面banner',
  'banner尺寸 1920*200px（大板块的专题，如促销累专题等）；',
  '标题文字大小26px，行高34px，正常体Regular，距下20px；',
  '介绍文字大小14px，行高22px，正常体Regular。',
  'FS Seamless Wi-Fi6 Solutions',
  'Accelerate and secure your wireless connerctivity'
];

export { dataJson };
