const data = [
  '弹出层 Pop-up Layer',
  '弹出层大小、无操作按钮弹窗、有操作按钮弹窗',
  '弹出层 Pop-up Layer',
  '模拟系统的消息提示框而实现的一套模态对话框组件，用于消息提示、确认消息和提交内容。',
  '弹层都为圆角矩形，圆角大小为3px。',
  '880px',
  '最大弹层宽度，用于视频弹窗。',
  '750px',
  '主要用于加购成功及产品快速预览弹窗。',
  '680px',
  '用于大多数弹窗，如取消订单、修改编辑地址、操作成功提示等。',
  '480px',
  '用于一些小的提示弹窗，如邮编设置等弹出层。',
  '无操作按钮',
  '通常用于操作成功的反馈弹窗。',
  'Your PO was submitted successfully.',
  'We will help to process the order within 12-24 hours, and you also can view update ', 
  'status through account center.',
  '弹窗标题文字大小 16px，颜色',
  '弹窗内容文字大小 13px，颜色',
  '标题文字与内容文字间距 14px，上下边距 32px，左边距 40px',
  '右侧关闭图标边距均为24px',
  '有操作按钮',
  '通常用于聚合信息、按钮的弹窗。',
  '关闭按钮为 16×16px ，默认颜色',
  'hover颜色',
  '操作按钮右边距 24px，下边距40px',
  '有操作按钮、表单、标题的弹窗',
  '通常用于聚合表单、信息、按钮的弹窗。',
  'Update Address',
  '*Please edit and update your address.',
  '*A signature is required for delivery.We do not ship to PO Boxes.',
  '弹窗标题文字大小 20px，颜色',
  '弹窗内容文字大小 13px，颜色',
  '标题文字上下间距 20px，左边距 24px',
  '内容文字边距均为40px',
  '关闭图标边距均为24px',
  '操作按钮边距为40px'
];

export { data };
