const data = [
  '内容导航 Content Navigation',
  '面包屑、分页、步骤条、标签页、下拉菜单',
  '面包屑',
  '面包屑是一种辅助的导航方式，通过表达内容归属关系，来告知用户当前所处的位置，并提供给用户返回至上一层级或最开始的起点的路径。',
  'Home',
  'My Account',
  'Account Settings',
  '分页',
  '当页面内需要展示的条目超过一定数量时，可将其分成多个页面进行分页加载处理，使用分页器快速切换页码。',
  '数字分页',
  '最完整的分页形式，包含翻页按钮、页数、每页显示数字条款。',
  '当页数处于首页、尾页时，上一页、下一页按钮分别置灰显示且不可点击。当前页所在页数为选中状态时，数字没有点击效果。',
  '当只有1页时，隐藏分页控件。每页显示多少的控件有24、36、48三个选项，根据实际设计选择是否使用该控件。',
  '默认',
  'Hover',
  '切换后',
  '步骤条',
  '步骤条通过展示任务流程的方向和关键步骤节点，引导用户按照流程完成任务，帮助用户了解操作流程长度和当前操作进度。',
  '横向步骤条',
  '横向步骤条一般置于页面顶部横向展示，建议步骤不超过5步。',
  'Click "Returns & Refunds" below to get started.',
  'After an approval, return items with an RMA form.',
  'FS will inspect the items once received.',
  'The replacement will be shipped out.',
  '纵向步骤条',
  '纵向步骤条一般置于页面左侧竖向展示，可展示多步骤。',
  '标签页',
  '标签页组织了相同层级的内容组，并允许用户在内容组之间点击切换，不必跳转页面。标签页统领整个页面或模块的内容，同时具有全局导航的作用。',
  '标准线条式标签页以文字加下划线的形式展示，是最常用的一种形式。',
  'Specifications',
  'Network Connectivity',
  'Product Highlights',
  'Community',
  'Q&A',
  'Reviews',
  'Resources',
  'Overview',
  'Spotlight',
  'Products',
  'Resources',
  '下拉菜单',
  '展示折叠的下拉菜单，用于拓展导航承载层级，站点地图式导航可以让用户对整个网站的可用功能一目了然。',
  '账户下拉菜单',
  'Sign in',
  'Need Help下拉菜单',
  'Live chat with us',
  'Live chat',
  'Get technical support',
  'Ask an Expert',
  'Send us a message',
  'Email Now',
  'Want to call?',
  '+1 (888) 468 7419'
];

export { data };
