const dataJson = [
  '文本录入 Text Entry',
  '文本框、文本域、搜索',
  '文本框',
  '输入框为用户提供了编辑文本的控件，是录入数据最基础和常见的方式。',
  '输入较少的字符总数，使用单行的输入形式，输入框高度（包含边框）38px，圆角3px，宽度根据页面进行适应。',
  '输入框',
  '交互：鼠标移入文本框区域，指针变为文本选择状态。',
  'Company Name (optional)',
  '触发输入',
  '交互：鼠标点击触发输入，文本框提示消失，文本框边框需与默认状态有区别。',
  'Email address',
  '输入内容',
  'Email address',
  '12306@fs.com',
  '表单验证',
  '交互：有输入验证、即时报错和提交验证，验证提示显示在文本框下方，再次编辑时，验证提示语随着编辑内容实时变化。',
  'Email address',
  'Please enter a valid email address.',
  '禁用状态',
  '交互：文本框无法操作时，文本框喝文本框内容需置灰显示，鼠标移入后，指针变为鼠标箭头（不使用禁用符号）。',
  'Email address',
  '文本域',
  '录入长篇幅的单一的文本使用多行的文本区域。',
  '文本域固定总高度为100px，宽度根据实际设计制定；文字距边框上下各10px，左右各12px。',
  '默认状态',
  '字符限制默认显示在输入框右上方。',
  'Tell us you need to apply for a sample product ID ',
  '输入状态状态',
  '字符输入中显示。',
  'Tell us your purpose for the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online. ',
  '超出状态',
  '输入超过设定字数会变红，且不能继续输入。',
  'the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or online.the sample application or or the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or online.the sample application or orthe sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or online.the sample application or orthe sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or online.the sample application or orthe sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or share your descriptions,quantities to the items that you need to apply for a sample if no product ID online.the sample application or online.the sample application or or or ',
  '搜索',
  '根据用户输入的内容，在可能的信息中实时匹配或联想以缩小范围、快速查找目标内容。是用户高效完成输入、获取信息的重要途径。',
  '默认状态',
  'Search',
  '输入关键词有结果',
  '输入关键词无结果',
  '搜索结果最多展示3个，点击可以删除。',
  'Recent Search',
  's5860',
  'Hot Search',
  'Change',
  's580',
  'access point',
  'access point',
  'qsfp28',
  'cwdm',
  'fiber optic cable',
  'media converter',
  'ethernet cable',
];

export { dataJson };
