const data = [
  '数据格式 Data Format',
  '数值、金额',
  '数值',
  '数值用来表示计量大小，可单独出现或搭配数字符号进行使用。',
  '符号格式',
  '千分位',
  '计量单位',
  '百分比',
  '正斜杠',
  '如何使用及合适使用',
  '默认使用千分位帮助用户阅读',
  '计量单位默认用小写字母',
  '比例问题等',
  '用分数的形式表示事项进展',
  '例子',
  '123,220',
  '123,220kg',
  '12.32%',
  '0/500',
  '计量单位',
  '计量单位并默认右对齐。',
  '示例',
  'S3410-24TS-P, 24-Port Gigabit Ethernet Fully Managed Pro PoE+ Switch, 24 x PoE+ Ports @740W, with 2 x 10Gb SFP+ Uplinks and 2 x Combo SFP Ports, Broadcom Chip',
  'Summary (5 Items)',
  'Subtotal:',
  'C$ 17,808.60',
  'Shipping:',
  'Calculated at checkout',
  'Total:',
  'US$ 17,808.60',
  '(Shipping & Tax not included):',
  'Secure Checkout',
  'Create Quote',
  'Save Cart',
  'View Saved Carts',
  '金额',
  '小写金额',
  '规范格式为「货币符号＋金额」的格式，例如“US$2,145,00”。货币符号表示货币种类的符号代码。(特殊情况可进行调整)',
  '示例'
];

export { data };
