const data = [
  '异常 Abnormal',
  '异常页、空状态',
  '异常页',
  '当页面出现异常时展示，其包含以下要素：',
  '1.异常代码/问题：当异常有具体的 HTTP 错误代码时，可予以展示；',
  '2.异常描述：简明扼要地描述异常原因，方便用户对问题做出反馈；',
  '3.建议操作：协助用户处理异常，或把用户引导回正确的路径上。',
  '模板 - 404',
  '当用户请求访问的页面、项目、资源等未找到时可使用。',
  '加载失败',
  '当页面因为网络等各种原因加载内容失败时展示，一般结合重试操作。',
  '空状态',
  '任何内容区域（页面、区块、组件、单数据）没有内容/数据显示给用户时，就会出现空状态。',
  '无数据',
  '内容区域无数据的场景使用，由图形元素、提示信息、建议操作三类元素组合展示，根据使用场景决定是否提供建议操作。',
  'All Time Frame',
  'Order #,item #',
  '35 Results',
  'If you can’t locate your orders, try selecting different filter conditions',
  'Private orders',
  'All Online Orders',
  'All Time Frame',
  'Search',
  'No Orders Found',
  'Start Shopping',
  'Shipping Addresses',
  'Billing Address',
  'Create a New Shipping Address',
  'No Shipping Address History.',
  'Create a New Shipping Address'
];

export { data };
